version: "3.7"
services:
  # Java 应用服务
  esdemo:
    image: ccr.ccs.tencentyun.com/mmkj_1_20241218/repository_20241218:v1 # 你构建的 Java 镜像
    container_name: esdemo
    environment:
      - JAVA_OPTS="-Xms512m -Xmx512m -Djava.security.egd=file:/dev/./urandom"
      - ARGS=""
    ports:
      - "8080:8080"  # 将容器的 8080 端口映射到宿主机
#    volumes:
#      - ./data/logs:/data/logs
    networks:
      - es-net

  # Filebeat 服务
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.14.1
    container_name: filebeat
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  # 让 Filebeat 访问 Docker 守护进程
      - /data/logs:/data/logs:ro  # 如果你想直接读取容器日志文件
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro # 映射 filebeat 配置文件
    environment:
      - "filebeat.config.modules.path=/usr/share/filebeat/modules.d/*.yml"
    command: ["filebeat", "-e"]
    networks:
      - es-net

  # Logstash（可选）
networks:
  es-net:
    external: true
